packages:
  - 'apps/*'
  - 'packages/*'
  - 'tooling/*'
allowBuilds:
  '@prisma/engines': true
  argon2: true
  better-sqlite3: true
  esbuild: false
  msw: true
  prisma: true
  sharp: false

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
